const FETCH_FORECAST_PENDING = "FETCH_FORECAST_PENDING";
const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";
const FETCH_FORECAST_ERROR = "FETCH_FORECAST_ERROR";

export { FETCH_FORECAST_PENDING, FETCH_FORECAST_SUCCESS, FETCH_FORECAST_ERROR };
